name: project_signup_page
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: 0.13.6
  sizer: ^2.0.15
  intl: ^0.18.0
  flutter_material_color_picker: ^1.1.0+2
  floating_bottom_navigation_bar: 1.5.2
  scroll_snap_list: ^0.8.4
  modal_bottom_sheet: 2.1.2
  vertical_weight_slider: 2.5.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: Font/Poppins/Poppins-Regular.ttf
        #- asset: Font/Poppins/Poppins-semiBoldItalic.ttf
  assets:
    - image/Treatments.png
    - image/Skin1.png
    - image/breast-cancer.png
    - image/BloodGroup1.png
    - image/Maharashtra.png
    - image/Gujarat.png
    - image/Rajasthan.png
    - image/Employed.png
    - image/Retired.png
    - image/ABHAGROUP.png
    - image/Phone.png
    - image/Adhar.png
    - image/squre.png
    - image/AbhaDP.png
    - image/GreenAerrow.png
    - image/QR.png
    - image/endocrine1.png
    - image/Boss.png
    - image/woman.png
    - image/neurology.png
    - image/ic_married.png
    - image/ic_divorce.png
    - image/diarrhea.png
    - image/SadImage.png
    - image/Noimage.png
    - image/Venereal.png
    - image/Heart22.png
    - image/muscle.png
    - image/skinn.png
    - image/Endocrine.png
    - image/SomeImage.png
    - image/lungs.png
    - image/TB.png
    - image/HIV.png
    - image/SoreThroat.png
    - image/Single.png
    - image/Dogg.png
    - image/Drugs.png
    - image/EditTab.png
    - image/Arrow.png
    - image/Latex.png
    - image/Pollen.png
    - image/Food.png
    - image/Insect.png
    - image/Dust.png
    - image/wheel.png
    - image/Polygon2.png
    - image/Peaceful.png
    - image/Sad.png
    - image/Cry.png
    - image/scalpel.png
    - image/rightlogo.png
    - image/wrongLogo.png
    - image/LifeStyle.png
    - image/OtherQue.png
    - image/systematization.png
    - image/i.png
    - image/ADDD.png
    - image/DropDown.png
    - image/Checkbox.png
    - image/Diet.png
    - image/Hospitazation.png
    - image/Veg.png
    - image/Lunch.png
    - image/Nonveg.png
    - image/Doctor.png
    - image/Exercise.png
    - image/EyeButton.png
    - image/EditButton.png
    - image/DeleteButton.png
    - image/ViewButton.png
    - image/PlusButton.png
    - image/Breakfast.png
    - image/Camera.png
    - image/Upload.png
    - image/doc.jpeg
    - image/Wheat.png
    - image/Unckecked.png
    - image/Rice.png
    - image/Checked.png
    - image/Vector.png
    - image/Dinner.png
    - image/Ellipse.png
    - image/Ellipse2.png
    - image/perso.png
    - image/Rectangle.png
    - image/Otpapage.png
    - image/google.png
    - image/born.png
    - image/Female1.png
    - image/Male1.png
    - image/other1.png
    - image/Plan1.png
    - image/Plan2.png
    - image/India.png
    - image/Dashboard.png
    - image/D.png
    - image/DD1.png
    - image/DD2.png
    - image/D3.png
    - image/DD4.png
    - image/DD5.png
    - image/Fitness2.png
    - image/D6.png
    - image/DDD7.png
    - image/D8.png
    - image/D9.png
    - image/Home.png
    - image/Documents.png
    - image/Microphone.png
    - image/Union.png
    - image/Abha.png
    - image/Frame4.png
    - image/Email1.png
    - image/file3.png
    - image/Heart1.png
    - image/Welcome1.png
    - image/Pulse.png
    - image/Patient.png
    - image/Steps.png
    - image/Calories.png
    - image/Bpressure.png
    - image/num.png
    - image/Minimum.png
    - image/Maximum.png
    - image/110%.png
    - image/icon.png
    - image/Ox.png
    - image/Normal.png
    - image/High.png
    - image/Stepss.png
    - image/Fire1.png
    - image/Place.png
    - image/Clock.png
    - image/stat.png
    - image/Daily.png
    - image/Dates.png
    - image/StepVec.png
    - image/Dates2.png
    - image/Calendar.png
    - image/480KCL.png
    - image/AvgBurn.png
    - image/Goal.png
    - image/Graph.png
    - image/Line.png
    - image/Edit.png
    - image/delete.png
    - image/accescode.png
    - image/Healthsummary.png
    - image/DoctorsSummary.png
    - image/BabyBorn.png
    - image/DeliveryTime.png
    - image/Watch1.png
    - image/Sym.png
    - image/DD7.png
    - image/Polygon.png
    - image/DDD8.png
    - image/DoctorZone.png
    - image/Dp.png
    - image/DD9.png
    - image/DD10.png
    - image/CaseBack.png
    - image/Home2.png
    - image/File12.png
    - image/Records.png
    - image/Mic1.png
    - image/Abha1.png
    - image/Pulse1.png
    - image/Patient1.png
    - image/Step1.png
    - image/Calories1.png
    - image/AccessCode1.png
    - image/health1.png
    - image/Doctor1.png
    - image/Ecliose1.png
    - image/Ellipse4.png
    - image/BP1.png
    - image/BP2.png
    - image/Min1.png
    - image/Circle1.png
    - image/Sleep.png
    - image/Fire3.png
    - image/Oxy1.png
    - image/Art1.png
    - image/110%1.png
    - image/Cal2.png
    - image/Vec2.png
    - image/F5.png
    - image/Firee.png
    - image/Place2.png
    - image/Clock1.png
    - image/AerrowRight.png
    - image/A1.png
    - image/Avoice1.png
    - image/voiceassis.png
    - image/Update1.png
    - image/Viewvoice1.png
    - image/trash1.png
    - image/Circles1.png
    - image/Bmi1.png
    - image/Bmi2.png
    - image/Lines.png
    - image/Reports.png
    - image/Report1.png
    - image/placeholder.png
    - image/profilrside.png
    - image/Vactinationnew.png
    - image/Profilewrite.png
    - image/FamiltHistory.png
    - image/Faimlymemmber.png
    - image/Profileupdate.png
    - image/Resend.png
    - image/AddButton.png
    - image/UploadFile.png
    - image/UPFile.png
    - image/Insorance.png
    - image/Settings.png
    - image/Cross.png
    - image/Faq.png
    - image/Logout.png
    - image/familyreport.png
    - image/adduserfaq.png
    - image/lorempluse.png
    - image/ic_settings_invitefriends.png
    - image/ic_settings_security.png
    - image/ic_settings_notification.png
    - image/ic_settings_compliant.png
    - image/ic_settings_termsandcondition.png
    - image/ic_settings_logout.png
    - image/forgetpassword.png
    - image/user_one.png
    - image/basic_edit.png
    - image/location.png
    - image/contact_info.png
    - image/dialog_cancel.png
    - image/correct.png
    - image/gmail.png
    - image/nott.png
    - image/menu.png
    - image/skinnew.png
    - image/lungsnew.png
    - image/kidneynew.png
    - image/endocrinenew.png
    - image/neurologynew.png
    - image/musclenew.png
    - image/bossnew.png
    - image/womannew.png
    - image/dermatologist.png
    - image/dentalcare.png
    - image/neurology.png
    - image/cardiologist.png
    - image/oncologist.png
    - image/pediatrics.png
    - image/medical.png
    - image/psychologist.png
    - image/doctorimg.png
    - image/menuimg.png
    - image/salary.png
    - image/medal.png
    - image/team.png
    - image/EyeButton.png
    - image/EditButton.png
    - image/DeleteButton.png
    - image/followups.png
    - image/testfollowups.png
    - image/yes.png
    - image/no.png
    - image/notgiven.png
    - image/due.png
    - image/given.png
    - image/boosterdose.png
    - image/vaccimg.png
    - image/checksquareyes.png
    - image/checksquareno.png
    - image/insurancecenter.png
    - image/certification.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
